### ISSUE TITLE
Réglage du son

### ISSUE THREAD

**Issue by prunkdump** [prunkdump/variometer-kits#1]
<a href="https://github.com/jpg63"><img src="https://avatars3.githubusercontent.com/u/26072646?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jpg63](https://github.com/jpg63)**
_Sun Apr 30 08:22:22 2017_
_Originally opened as https://github.com/prunkdump/arduino-variometer/issues/2_

----

Le son est un peu fort et il serait intéressant de le régler

Priorité : Indispensable

solution :

Pour le volume c'est effectivement possible de le régler avec le code. Je comptais faire la modif. Il faut remplacer tous les toneAC(freq) en toneAC(freq, VOLUME) avec un volume entre 1 et 10. Mais encore une fois il faut que j'explique comment mettre à jour le code.

**Comment by prunkdump** [comment]
<a href="https://github.com/van-hurlu"><img src="https://avatars0.githubusercontent.com/u/28158829?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [van-hurlu](https://github.com/van-hurlu)**
_Sun Apr 30 08:34:10 2017_

----

Très facile mettre le code à jour, je l'ai fait pour faire fonctionner le baro
si j'ai pigé ma manip
il suffit d'ajouter ,5 juste après la valeur freq dans le code
ou mieux de créer un int vol
de déclarer au début la valeur vol = 5
et de mettre ,vol après la valeur freq dans le code

**Comment by van-hurlu** [comment]
cela semble encore plus simple
la valeur du volume semble être définie à la ligne 106 de toneAC.h
Je me trompe ?

**Comment by jpg63** [comment]
je viens de parcourir le code, je pense qu'il faut modifier la bibliothèque beeper. Pour pouvoir avoir la variable volume son dans le programme principale et par la suite pouvoir le récupérer d'un fichier de config sur la carte SD, on peut l’intégrer dans la fonction beeper. Modification de SetTone pour intégrer le volume

**Comment by jpg63** [comment]
[fichiers.zip](https://github.com/prunkdump/variometer-kits/files/966859/fichiers.zip)

**Comment by prunkdump** [comment]
Ton code a été intégré !

On peux maintenant régler le volume avec la valeur "VARIOMETER_BEEP_VOLUME" dans "variometer.ino".

Testez ce que ça donne !

**Comment by jpg63** [comment]
Le réglage du son fonctionne

**Comment by prunkdump** [comment]
Nickel !

Merci pour le debug  et le code !
