### ISSUE TITLE
charge batterie

### ISSUE THREAD

**Issue by prunkdump** [prunkdump/variometer-kits#4]
<a href="https://github.com/jpg63"><img src="https://avatars3.githubusercontent.com/u/26072646?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jpg63](https://github.com/jpg63)**
_Sun Apr 30 08:37:07 2017_
_Originally opened as https://github.com/prunkdump/arduino-variometer/issues/5_

----

connaitre la charge de la batterie

**Comment by jpg63** [comment]
Une idée pour connaitre la capacité de la batterie serait de raccorder la patte RAW à l'entrée A1

ensuite on mesure la tension sur l'entrée A1 

Les batteries lipo n'ont pas une décharge linéaire mais il existe des tables qui donne une bonne idée de la charge

Si la tension mesuré est supérieur à 4.2 la batterie est full = 100%
en dessous de 3.683v c'est 0 est la batterie est pas loin d'être morte si elle n'est pas vite chargée

implémenter la table {tension, % capacité)

{{3, 0}, {3.093, 1}, {3.196, 2}, {3.301, 3}, {3.401, 4}, {3.477, 5}, {3.544, 6}, {3.601, 7}, {3.637, 8}, {3.664, 9}, 
{3.679, 10}, {3.683, 11}, {3.689, 12}, {3.692, 13}, {3.705, 14}, {3.71, 15}, {3.713, 16}, {3.715, 17}, {3.72, 18}, {3.731, 19}, 
{3.735, 20}, {3.744, 21}, {3.753, 22}, {3.756, 23}, {3.758, 24}, {3.762, 25}, {3.767, 26}, {3.774, 27}, {3.78, 28}, {3.783, 29}, 
{3.786, 30}, {3.789, 31}, {3.794, 32}, {3.797, 33}, {3.8, 34}, {3.802, 35}, {3.805, 36}, {3.808, 37}, {3.811, 38}, {3.815, 39}, 
{3.818, 40}, {3.822, 41}, {3.825, 42}, {3.829, 43}, {3.833, 44}, {3.836, 45}, {3.84, 46}, {3.843, 47}, {3.847, 48}, {3.85, 49}, 
{3.854, 50}, {3.857, 51}, {3.86, 52}, {3.863, 53}, {3.866, 54}, {3.87, 55}, {3.874, 56}, {3.879, 57}, {3.888, 58}, {3.893, 59}, 
{3.897, 60}, {3.902, 61}, {3.906, 62}, {3.911, 63}, {3.918, 64}, {3.923, 65}, {3.928, 66}, {3.939, 67}, {3.943, 68}, {3.949, 69}, 
{3.955, 70}, {3.961, 71}, {3.968, 72}, {3.974, 73}, {3.981, 74}, {3.987, 75}, {3.994, 76}, {4.001, 77}, {4.007, 78}, {4.014, 79}, 
{4.021, 80}, {4.029, 81}, {4.036, 82}, {4.044, 83}, {4.052, 84}, {4.062, 85}, {4.074, 86}, {4.085, 87}, {4.095, 88}, {4.105, 89}, 
{4.111, 90}, {4.116, 91}, {4.12, 92}, {4.125, 93}, {4.129, 94}, {4.135, 95}, {4.145, 96}, {4.176, 97}, {4.179, 98}, {4.193, 99}, 
{4.2, 100}}

**Comment by jpg63** [comment]
j'ai parcouru le projet de sinseman, il mesure la tension de la batterie en utilisant A0.

Dans le kit, il est simple de mettre un petit fil entre la patte RAW et A3 pour avoir l'affichage de la tension de la batterie. En fonction de la mémoire, soit on peut implémenter un pourcentage avec une table de conversion (juste mais gourmande en mémoire et en instructions) ou un graph simplifier avec une approximation linéaire

**Comment by jpg63** [comment]
Mon idée :
Modifier la bibliothèque varioscreen pour ajouter 5 symboles, batterie vide, à 25%, à 50%, à 75% et à 100%.
Ajout de 5 fonctions display

dans variometer.ino  
- on aura la lecture de A0
- le calcul : %=(T-3.5534)/0.0059
- le test d'intervalle et affichage
                     %>75%                   batterie 100%
                     %>50                      batterie 75%
                     %>25                       batterie 50%
                     %<25                       batterie 25%
                     tension <= 3.683v   batterie vide

**Comment by prunkdump** [comment]
Je pense effectivement que c'est grandement suffisant.

Une fois que tu maîtrisera l'affichage sur le 5110 du pourras peut être optimiser le code comme suit : 

Au lieu de stocker 4 symboles : 
[###]
[  ##]
[    #]
[      ]

Tu peux stocker trois petits symboles : 
[
]
#

Et construire l'affichage du diagramme avec le code.

**Comment by jpg63** [comment]
oui, si on peut afficher un symbole de 1 octet, et faire une boucle

on pourrait tout faire avec un 0xff et un 0x81 après 3 octets pour le bout de la batterie 0xff,0x3c,0x3c

si le corps de la batterie fait 10 octets on aura 1 octet pour 10% le code du coup pourrait être très simple 1 boucle et un test

**Comment by jpg63** [comment]
Au niveau de l'entrée analogique, il va falloir ajouter un pont diviseur

L'arduino étant une version 3.3V sa tension de référence est 3.3V
pour 1024 on aura 3.3V donc si on veut mesurer 4.2V max pas le choix il faut mettre un petit pont diviseur en entrée
3.3/4.2 = 0.7857 soit 1/1.27

R2/R1+R2 = 1/1.27
R1 relier à RAW et à R2
R2 relier à la masse et à R1
 
U  pris entre l'entrée du pont et la masse
U2 tension prise entre la sortie et la masse

U2 = U x (R2/(R1+R2))
4.2 / 1.27 = 3.3V

Ul=(val1/1024)*Vcc 
ou Ul est la tension lue, 
val1 la valeur retournée par AnalogRead(), 
et Vcc la tension d’alimentation du circuit

la tension de la batterie sera 

UI = 1.27 * (val1 /1024) * 3.3

pour R1 et R2 avec une impédance d'entrée de 100M on peut prendre R2 = 1M et R1 = 270K

![220px-pont_diviseur_tension svg](https://cloud.githubusercontent.com/assets/26072646/25698133/f0ee6c1e-30bd-11e7-9de6-7111ca57315f.png)
  
La tension mesurée au repos, indique pratiquement son niveau de charge: 4.2v=100% 3.97v=80% 3.87v=60% 3.79v=40% 3.7v=20% 3.3v=5% 3v=0

si on part avec 10 barres pour on peut remplir ou non la batterie en affichant 0xff ou 0x81 en fonction du test de la tension

**Comment by jpg63** [comment]
le code est sur le forum

Il me reste à tester et à valider la décharge de la batterie

**Comment by prunkdump** [comment]
Le code est intégré sur GitHub. L'approximation linéaire de la décharge de la batterie a été utilisée.
