### ISSUE TITLE
mettre à jour le firmware sans ouvrir le boitier

### ISSUE THREAD

**Issue by jpg63** [prunkdump/variometer-kits#5]
Pas pratique d'ouvrir le boitier pour mettre à jour le firmware

ma première idée de faire un trou sur le capot du boitier pour accéder au switch, n'est pas possible, le switch est juste sous l'écran

l'idée de mettre à jour le firmware à partir du moment ou un fichier FIRM.HEX est sur la carte SD me parait simple et très pratique. Dès que le vario est à jour, rien de bien compliquer que de l’éteindre et de  supprimer le fichier de la carte SD

**Comment by jpg63** [comment]
Astuce qui marche proposer par ptitkiki sur le forum du chant du vario

Concernant le reset non accessible, j'ai fait une petite mod qui marche impec :  j'ai routé la pin "rst" de l'arduino vers une pin Data non utilisée sur le port µUSB.
J'ai sacrifié une prise mâle pour faire un shunt externe entre gnd et la pin cablée.
Il suffit de brancher la prise momentanément pour faire un reset, c'est trés pratique. (cf fil jaune et prise shunté ci dessous):

![811389img20170502232731hdr](https://cloud.githubusercontent.com/assets/26072646/25707931/4baeb6fa-30e5-11e7-9b85-ce559215a3ee.jpg)

**Comment by jpg63** [comment]
Message du forum publié le 04/04/2017 par prunkdump
-> Téléchargez la dernière version du code https://github.com/prunkdump/arduino-variometer et compiler variometer.ino
-> Chargez le code avec la SDCard et le bouton reset (pour la dernière fois  Clin d'oeil )
-> Remontez le boîtier.

Pour mettre à jour le firmware par la suite :

-> éteindre le vario
-> le retouner face posé vers le bas sur une table
-> mettre sous tension
-> au bout d'un moment il fait 3 bips longs.
-> pendant ces bips retourner le vario pour qu'il ne relance pas la mise à jour à nouveau au prochain démarrage.

Voilà.

**Comment by prunkdump** [comment]
Le bootloader est maintenant lancé si le vario est orienté vers le sol lors du démarrage.
