### ISSUE TITLE
Affichage de l'heure et de la durée du vol

### ISSUE THREAD

**Issue by jpg63** [prunkdump/variometer-kits#8]
Il serait intéressant de récupérer l'heure via le GPS et de l'afficher en alternance avec la durée du vol

La durée du vol pourrait être calculer en faisant la soustraction de l'heure de déclenchement du vol et de l'heure actuelle

3 fonctions 

1- récupération de l'heure GPS
2- conversion heure NMEA en seconde
3 - conversion de seconde en HH:MM

**Comment by prunkdump** [comment]
L'affichage de l'heure est du temps de vol est maintenant implémenté. Merci jpg63 !

**Comment by jpg63** [comment]
Salut,


du coté de la compilation, j'ai un arduino portable et des batchs de compilations. Il me reste quelques réglages (librairie du projet)et des tests à faire et ce sera bon.


Je vais bientôt publier une version avec l'affichage de la version (en trichant un peu, le code ne grossit presque pas) et une alternative au double écran (mono écran made in jpg63 😉)


A+


jean-philippe


________________________________
De : prunkdump <notifications@github.com>
Envoyé : mardi 13 juin 2017 20:50
À : prunkdump/variometer-kits
Cc : jpg63; Author
Objet : Re: [prunkdump/variometer-kits] Affichage de l'heure et de la durée du vol (#8)


L'affichage de l'heure est du temps de vol est maintenant implémenté. Merci jpg63 !
